version: 2
jobs:
  release:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
            qio platform install https://github.com/OS-Q/P12/releases/latest/download/P12.zip
      - run:
          name: "Build"
          command: |
            qio run -d examples/arduino-blink
            qio run -d examples/arduino-own-src_dir
            qio run -d examples/MPU_Speed_Setting

  latest:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            qio run -d examples/arduino-blink
            qio run -d examples/arduino-own-src_dir
            qio run -d examples/MPU_Speed_Setting

workflows:
    version: 2
    run_ci:
        jobs:
            - release
            - latest
