name: nightly

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    name: QIO
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]
        examples:
          - "arduino-blink"
          - "arduino-own-src_dir"
          - "MPU_Speed_Setting"

        package:
          - "release"
          - "latest"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install release
        if: matrix.package == 'release'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          pio platform install file://.

      - name: Install QIO
        if: matrix.package == 'latest'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.examples }}

  platformio:
    name: PIO
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]
        example:
          - "examples/Blink"
          - "examples/MPU_Speed_Setting"


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: darkautism/pio-lgt8fx
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: GH_Repo

      - name: Install dependencies
        working-directory: GH_Repo
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        working-directory: GH_Repo
        run: |
          pio run -d ${{ matrix.example }}
